// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: IM.Login.proto

#include "IM.Login.pb.h"
#include "IM.Login.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace IM {
namespace Login {

static const char* ImLogin_method_names[] = {
  "/IM.Login.ImLogin/Regist",
  "/IM.Login.ImLogin/Login",
};

std::unique_ptr< ImLogin::Stub> ImLogin::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImLogin::Stub> stub(new ImLogin::Stub(channel, options));
  return stub;
}

ImLogin::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Regist_(ImLogin_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(ImLogin_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ImLogin::Stub::Regist(::grpc::ClientContext* context, const ::IM::Login::IMRegisterReq& request, ::IM::Login::IMRegisterRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IM::Login::IMRegisterReq, ::IM::Login::IMRegisterRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Regist_, context, request, response);
}

void ImLogin::Stub::async::Regist(::grpc::ClientContext* context, const ::IM::Login::IMRegisterReq* request, ::IM::Login::IMRegisterRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IM::Login::IMRegisterReq, ::IM::Login::IMRegisterRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Regist_, context, request, response, std::move(f));
}

void ImLogin::Stub::async::Regist(::grpc::ClientContext* context, const ::IM::Login::IMRegisterReq* request, ::IM::Login::IMRegisterRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Regist_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::IM::Login::IMRegisterRes>* ImLogin::Stub::PrepareAsyncRegistRaw(::grpc::ClientContext* context, const ::IM::Login::IMRegisterReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::IM::Login::IMRegisterRes, ::IM::Login::IMRegisterReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Regist_, context, request);
}

::grpc::ClientAsyncResponseReader< ::IM::Login::IMRegisterRes>* ImLogin::Stub::AsyncRegistRaw(::grpc::ClientContext* context, const ::IM::Login::IMRegisterReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegistRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ImLogin::Stub::Login(::grpc::ClientContext* context, const ::IM::Login::IMLoginReq& request, ::IM::Login::IMLoginRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IM::Login::IMLoginReq, ::IM::Login::IMLoginRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void ImLogin::Stub::async::Login(::grpc::ClientContext* context, const ::IM::Login::IMLoginReq* request, ::IM::Login::IMLoginRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IM::Login::IMLoginReq, ::IM::Login::IMLoginRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void ImLogin::Stub::async::Login(::grpc::ClientContext* context, const ::IM::Login::IMLoginReq* request, ::IM::Login::IMLoginRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::IM::Login::IMLoginRes>* ImLogin::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::IM::Login::IMLoginReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::IM::Login::IMLoginRes, ::IM::Login::IMLoginReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::IM::Login::IMLoginRes>* ImLogin::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::IM::Login::IMLoginReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

ImLogin::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImLogin_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImLogin::Service, ::IM::Login::IMRegisterReq, ::IM::Login::IMRegisterRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ImLogin::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IM::Login::IMRegisterReq* req,
             ::IM::Login::IMRegisterRes* resp) {
               return service->Regist(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImLogin_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImLogin::Service, ::IM::Login::IMLoginReq, ::IM::Login::IMLoginRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ImLogin::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IM::Login::IMLoginReq* req,
             ::IM::Login::IMLoginRes* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
}

ImLogin::Service::~Service() {
}

::grpc::Status ImLogin::Service::Regist(::grpc::ServerContext* context, const ::IM::Login::IMRegisterReq* request, ::IM::Login::IMRegisterRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ImLogin::Service::Login(::grpc::ServerContext* context, const ::IM::Login::IMLoginReq* request, ::IM::Login::IMLoginRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace IM
}  // namespace Login

